### ISSUE TITLE
Text garbage in the middle of file

### ISSUE THREAD

**Issue by pmoura** [vscosta/yap-6.3#43]
https://github.com/vscosta/yap-6.3/blob/13d88949c95ced7a84999a950ee37d4723e8a278/library/prandom.yap#L46

**Comment by pmoura** [comment]
The garbage text is followed by an `initialization/1` directive. As a consequence, YAP compiles instead a `vvvvvv  :- initialization (..)` clause!

**Comment by vscosta** [comment]
got it at last

**Comment by pmoura** [comment]
Fixed in e894209836a5dd4a7c54ae0d3e2b8a29e0673345.
