### ISSUE TITLE
Typo in variable name in clause for predicate assertall/2

### ISSUE THREAD

**Issue by pmoura** [vscosta/yap-6.3#48]
Typo in variable name in clause for predicate `assertall/2`:

https://github.com/vscosta/yap-6.3/blob/61adeeeb5c8d9c93786528e8d1f4bbd4652839a7/library/ytest.yap#L165-L167

`REfs`  should be `Refs`. Found by the Logtalk linter.

**Comment by vscosta** [comment]
thanks!

**Comment by pmoura** [comment]
Fixed in e894209836a5dd4a7c54ae0d3e2b8a29e0673345.
