### ISSUE TITLE
Wrong closure number in meta-predicate directive

### ISSUE THREAD

**Issue by pmoura** [vscosta/yap-6.3#49]
The following meta-predicate directive is incorrect given the meta-call in the predicate definition:

https://github.com/vscosta/yap-6.3/blob/61adeeeb5c8d9c93786528e8d1f4bbd4652839a7/library/mapargs.yap#L43

It should be instead:

```logtalk
mapargs_args(3,+,-,-,-,+),
```

Found by the Logtalk linter.

**Comment by vscosta** [comment]
thanks!

**Comment by pmoura** [comment]
Fixed in e894209836a5dd4a7c54ae0d3e2b8a29e0673345.
