### ISSUE TITLE
BUILDING packages/CLPBN/horus works once -std=c++11 is part of CXX_FLAGS 

### ISSUE THREAD

**Issue by logicmoo** [vscosta/yap-6.3#9]
Workaround to compile for at least my machine..
after running

```
mkdir build
cd build
cmake .. -i
```

Afterwards ensure
Ensure  `-std=c++11` is part of `CXX_FLAGS` in these two files:

```
packages/CLPBN/horus/CMakeFiles/horus.dir/flags.make
packages/CLPBN/horus/CMakeFiles/HorusCli.dir/flags.make
```

Obviously we cannot add this globally though since other places like `CXX/`  the `-std=c++11`  would break things

**Comment by vscosta** [comment]
The horus. Cmake file is supposed to do that

It may be you use anold cmake?

**Comment by logicmoo** [comment]
I just now saw the github message from 10 days ago.. 

The problem went away I had assumed you changed something to fix it 

But I did actually update Cmake and indeed..  maybe that is why the problem went away :)

**Comment by vscosta** [comment]
Are you using Windows? What kind of setup?

On Wed, Feb 24, 2016 at 10:33 AM, Douglas R. Miles <notifications@github.com

**Comment by logicmoo** [comment]
Windows XP with Visual Studio 6.0  in a VMWare on

I have Windows 10 running  VS2008 - VS2015 (all editions) + MSY2


My ideal would be to compile YAP on visual studio (Any version)

But would live with MSYS/MinGW if we had to.


(The reason for the VS interest is it will make debugging/developing in the
CLR/MONO easier)






MSYS2 output

Administrator@I74930K MINGW64 /c/Users/Administrator
$ pacman -Q
asciidoc 8.6.9-4
autoconf 2.69-3
autoconf2.13 2.13-2
autogen 5.18.4-2
automake-wrapper 10-1
automake1.10 1.10.3-3
automake1.11 1.11.6-3
automake1.12 1.12.6-3
automake1.13 1.13.4-4
automake1.14 1.14.1-3
automake1.15 1.15-2
automake1.6 1.6.3-2
automake1.7 1.7.9-2
automake1.8 1.8.5-3
automake1.9 1.9.6-2
bash 4.3.042-4
bash-completion 2.1-6
binutils 2.25.1-1
bison 3.0.4-1
bsdcpio 3.1.2-5
bsdtar 3.1.2-5
bzip2 1.0.6-2
ca-certificates 20150426-1
catgets 1.1-2
cloog 0.18.3-1
cmake 3.2.3-1
coreutils 8.24-1
crypt 1.1-6
ctags 5.8-1
curl 7.47.1-1
dash 0.5.8-1
db 5.3.28-2
diffstat 1.58-1
diffutils 3.3-3
docbook-xml 4.5-2
docbook-xsl 1.78.1-3
dos2unix 7.3.3-1
expat 2.1.0-2
file 5.25-1
filesystem 2015.04-3
findutils 4.6.0-1
flex 2.6.0-1
gawk 4.1.3-1
gcc 4.9.2-6
gcc-libs 4.9.2-6
gdb 7.9-1
gdbm 1.11-3
gettext 0.19.6-1
git 2.7.0-1
glib2 2.44.1-1
glib2-devel 2.44.1-1
gmp 6.1.0-1
gnupg 1.4.19-1
gperf 3.0.4-3
grep 2.22-1
groff 1.22.3-1
gzip 1.6-1
heimdal 1.5.3-8
heimdal-libs 1.5.3-8
help2man 1.47.3-1
icu 56.1-1
inetutils 1.9.2-1
info 6.0-1
intltool 0.51.0-2
isl 0.14.1-1
lemon 3.8.7.0-1
less 481-1
libarchive 3.1.2-5
libasprintf 0.19.6-1
libassuan 2.4.2-1
libbz2 1.0.6-2
libcatgets 1.1-2
libcrypt 1.1-6
libcurl 7.47.1-1
libdb 5.3.28-2
libedit 3.1-20150325
libexpat 2.1.0-2
libffi 3.2.1-1
libffi-devel 3.2.1-1
libgc 7.2.d-1
libgcrypt 1.6.4-1
libgdbm 1.11-3
libgettextpo 0.19.6-1
libgpg-error 1.21-1
libgpgme 1.6.0-1
libguile 2.0.11-3
libiconv 1.14-2
libiconv-devel 1.14-2
libidn 1.32-1
libintl 0.19.6-1
libltdl 2.4.6-1
liblzma 5.2.1-1
liblzo2 2.09-1
libmetalink 0.1.2-2
libnettle 3.1.1-1
libopenssl 1.0.2.d-1
libp11-kit 0.23.2-1
libpcre 8.38-1
libpcre16 8.38-1
libpcre32 8.38-1
libpcrecpp 8.38-1
libpcreposix 8.38-1
libpipeline 1.4.0-1
libreadline 6.3.008-7
libsqlite 3.10.0.0-1
libssh2 1.6.0-1
libtasn1 4.7-1
libtool 2.4.6-1
libunistring 0.9.6-1
libunrar 5.3.7-1
libutil-linux 2.26.2-1
libxml2 2.9.2-2
libxslt 1.1.28-7
llvm-svn 124592.2aebced-1
lndir 1.0.3-1
m4 1.4.17-4
make 4.1-4
man-db 2.7.4-1
mc 4.8.15-1
mingw-w64-i686-binutils 2.25.1-2
mingw-w64-i686-bzip2 1.0.6-4
mingw-w64-i686-crt-git 5.0.0.4609.566d621-1
mingw-w64-i686-expat 2.1.0-6
mingw-w64-i686-gcc 5.3.0-2
mingw-w64-i686-gcc-ada 5.3.0-2
mingw-w64-i686-gcc-fortran 5.3.0-2
mingw-w64-i686-gcc-libgfortran 5.3.0-2
mingw-w64-i686-gcc-libs 5.3.0-2
mingw-w64-i686-gcc-objc 5.3.0-2
mingw-w64-i686-gdb 7.10.1-1
mingw-w64-i686-gdbm 1.11-3
mingw-w64-i686-gettext 0.19.6-2
mingw-w64-i686-gmp 6.1.0-1
mingw-w64-i686-headers-git 5.0.0.4609.566d621-1
mingw-w64-i686-isl 0.15-1
mingw-w64-i686-libffi 3.2.1-3
mingw-w64-i686-libiconv 1.14-5
mingw-w64-i686-libmangle-git 5.0.0.4509.2e5a9a2-1
mingw-w64-i686-libsystre 1.0.1-2
mingw-w64-i686-libtre-git r122.c2f5d13-4
mingw-w64-i686-libwinpthread-git 5.0.0.4573.628fdbf-1
mingw-w64-i686-make 4.1.2351.a80a8b8-1
mingw-w64-i686-mpc 1.0.3-2
mingw-w64-i686-mpfr 3.1.3.p0-2
mingw-w64-i686-ncurses 6.0.20150627-2
mingw-w64-i686-openssl 1.0.2.e-1
mingw-w64-i686-pkg-config 0.29-1
mingw-w64-i686-python2 2.7.11-1
mingw-w64-i686-readline 6.3.008-1
mingw-w64-i686-tcl 8.6.4-2
mingw-w64-i686-termcap 1.3.1-2
mingw-w64-i686-tk 8.6.4-2
mingw-w64-i686-tools-git 5.0.0.4592.90b8472-1
mingw-w64-i686-windows-default-manifest 6.4-2
mingw-w64-i686-winpthreads-git 5.0.0.4573.628fdbf-1
mingw-w64-i686-zlib 1.2.8-9
mintty 1~2.2.3-1
mpc 1.0.3-1
mpfr 3.1.3.p0-1
msys2-keyring r9.397a52e-1
msys2-runtime 2.4.1.16860.40c26fc-1
msys2-runtime-devel 2.4.1.16860.40c26fc-1
msys2-w32api-headers 5.0.0.4574.ce1ad45-1
msys2-w32api-runtime 5.0.0.4574.ce1ad45-1
ncurses 6.0.20151121-1
openssh 7.1p2-1
openssl 1.0.2.d-1
p11-kit 0.23.2-1
p7zip 9.38.1-1
pacman 5.0.0.6348.cc5a8f1-1
pacman-mirrors 20160112-1
patch 2.7.5-1
patchutils 0.3.3-2
pax-git 20140703.2.1.g469552a-1
pcre 8.38-1
pcre-devel 8.38-1
perl 5.22.0-2
perl-Authen-SASL 2.16-2
perl-Convert-BinHex 1.123-2
perl-Encode-Locale 1.04-1
perl-Error 0.17024-1
perl-File-Listing 6.04-2
perl-HTML-Parser 3.71-3
perl-HTML-Tagset 3.20-2
perl-HTTP-Cookies 6.01-2
perl-HTTP-Daemon 6.01-2
perl-HTTP-Date 6.02-2
perl-HTTP-Message 6.06-2
perl-HTTP-Negotiate 6.01-2
perl-IO-Socket-SSL 2.016-1
perl-IO-stringy 2.111-1
perl-LWP-MediaTypes 6.02-2
perl-Locale-Gettext 1.05-4
perl-MIME-tools 5.506-1
perl-MailTools 2.14-1
perl-Module-Build 0.4212-1
perl-Net-HTTP 6.09-1
perl-Net-SMTP-SSL 1.02-1
perl-Net-SSLeay 1.70-1
perl-TermReadKey 2.33-1
perl-Test-Pod 1.50-1
perl-TimeDate 2.30-2
perl-URI 1.68-1
perl-WWW-RobotRules 6.02-2
perl-XML-Parser 2.44-1
perl-YAML-Syck 1.29-1
perl-libwww 6.13-1
pkg-config 0.28-2
pkgfile 15-1
python2 2.7.10-1
rcs 5.9.4-1
rebase 4.4.1-6
repman-git r23.87bf865-1
scons 2.4.1-2
sed 4.2.2-2
sqlite 3.10.0.0-1
swig 3.0.7-1
tar 1.28-3
texinfo 6.0-1
texinfo-tex 6.0-1
tftp-hpa 5.2-1
time 1.7-1
tzcode 2015.e-1
unrar 5.3.7-1
util-linux 2.26.2-1
vim 7.4.872-2
wget 1.17.1-2
which 2.21-2
windows-default-manifest 6.4-1
xmlto 0.0.26-2
xz 5.2.1-1
zlib 1.2.8-3
zlib-devel 1.2.8-3

Administrator@I74930K MINGW64 /c/Users/Administrator
$

**Comment by logicmoo** [comment]
In my reply I assumed the question wasn't related to CLPBN/Horus.. ( That was my linux machine that day where I had CMake issues..)

So I was answering your question based on the the notion you are working on getting us setup to also build from windows.

**Comment by vscosta** [comment]
OK, sorry about the confusion. I am indeed trying to compile YAP on windows
right now.



On Wed, Feb 24, 2016 at 11:08 AM, Douglas R. Miles <notifications@github.com

**Comment by logicmoo** [comment]
My normal setup is Ubuntu Linux 14.0.4

@vscosta  is you setup OSX?  mainly?

**Comment by vscosta** [comment]
Yes, also ubuntu, fedora.

On Wed, Feb 24, 2016 at 11:59 AM, Douglas R. Miles <notifications@github.com
